version: "3.7"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  web:
    build: './web'

  substractor:
    build: './substractor'
