version: "3.7"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  api:
    build: './api'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  substractor:
    build: './substractor'

  dashboard:
    build: './dashboard'
