version: "3.7"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bank
      - POSTGRES_USER=bank
      - POSTGRES_DB=bank

  nginx:
    build: './nginx'
    ports:
      - "80:80"

  api:
    build: './api'
    environment:
      - APP_POSTGRES_HOST=postgres
      - APP_POSTGRES_PORT=5432
      - APP_POSTGRES_USER=bank
      - APP_POSTGRES_PASSWORD=bank
      - APP_POSTGRES_DB=bank
    # TODO: убрать, когда прекратится разработка
    command: pipenv run adev runserver --port 80 app
    volumes:
      - "./api/:/api"
# TODO: разобраться, как рестартить сервисы
# WARNING: Some services (api) use the 'deploy' key, which will be ignored.
# Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm
#    deploy:
#      replicas: 2
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3

  subtractor:
    build: './subtractor'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=bank
      - POSTGRES_USER=bank
      - POSTGRES_DB=bank

  dashboard:
    build: './dashboard'
    environment:
      - API_HOST=http://api/
